### ISSUE TITLE
pims.api.UnknownFormatError: All handlers returned exceptions:

### ISSUE THREAD

**Issue by GenevieveBuckley** [monashmicroimaging/podocytes#15]
pims.api.UnknownFormatError: All handlers returned exceptions:
Mac High Sierra

```
/var/folders/gz/6f0v_zhs09x38mb4td_h6py80000gn/T/_MEIUq4lN2/tifffile/tifffile.py:7685: UserWarning: No module named 'tifffile._tifffile'
  Functionality might be degraded or be slow.

2018-05-30 12:38:52,748 Podocyte automated analysis program
2018-05-30 12:38:52,748 30-May-2018_12-38PM
2018-05-30 12:38:52,749 Processing file: /Users/genevieb/Documents/ImageAnalysis/kidney_glomeruli/input_data/SP8/Postnatal24week_mice/input_files/51512.lif
[73213] Failed to execute script launch-gui
/var/folders/gz/6f0v_zhs09x38mb4td_h6py80000gn/T/_MEIUq4lN2/pims/bioformats.py:53: UserWarning: loci_tools.jar not found, downloading
/var/folders/gz/6f0v_zhs09x38mb4td_h6py80000gn/T/_MEIUq4lN2/pims/api.py:206: UserWarning: <class 'pims.bioformats.BioformatsReader'> errored: Package loci.formats.ChannelFiller is not Callable
Traceback (most recent call last):
  File "bin/launch-gui.py", line 3, in <module>
  File "site-packages/gooey/python_bindings/gooey_decorator.py", line 89, in <lambda>
  File "podocytes/main.py", line 88, in main
  File "site-packages/pims/api.py", line 208, in open
pims.api.UnknownFormatError: All handlers returned exceptions:
<class 'pims.bioformats.BioformatsReader'> errored: Package loci.formats.ChannelFiller is not Callable

30-May-2018_12-38PM
```

**Comment by GenevieveBuckley** [comment]
The error makes it sound a little like the .lif image type is unrecognised, but this works just fine:

```
dyn-130-194-109-166:~ genevieb$ source activate podo
(podo) dyn-130-194-109-166:~ genevieb$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pims
>>> filename = "/Users/genevieb/Documents/ImageAnalysis/kidney_glomeruli/input_data/SP8/Postnatal24week_mice/input_files/51512.lif"
>>> images = pims.open(filename)
>>> images.metadata.ImageCount()
15
>>> 
```

**Comment by jni** [comment]
@GenevieveBuckley given this error, perhaps we should keep #8 and bioformats in mind as still an option? Or are you convinced that PIMS is the way of the future?

**Comment by GenevieveBuckley** [comment]
Cannot reproduce error in virtual test machine.
