### ISSUE TITLE
Error writing log file (possible issue related to spaces in directory path)

### ISSUE THREAD

**Issue by GenevieveBuckley** [monashmicroimaging/podocytes#22]
What even. Is this related to spaces in the directory path?
Or, maybe it's because I'm reading the data off an external hard drive rather than my local disk?

Note that `/Applications/DT/output_27June2018/` is NOT the output directory path entered into the Podo app. It's supposed to be `/Volumes/Genevieve/ImageAnalysis/kidney_glomeruli/input_data/SP8/Ageing and DT/output_27June2018/`

```
[91014] Failed to execute script launch-gui
Traceback (most recent call last):
  File "bin/launch-gui.py", line 3, in <module>
  File "site-packages/gooey/python_bindings/gooey_decorator.py", line 89, in <lambda>
  File "podocytes/main.py", line 71, in main
  File "podocytes/main.py", line 330, in log_file_begins
  File "logging/__init__.py", line 1030, in __init__
  File "logging/__init__.py", line 1059, in _open
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/DT/output_27June2018/log_podo_27-Jun-2018_12-27PM.log'
```

**Comment by jni** [comment]
Ah! It's what I suspected before! It's trying to write a log to that directory, but I imagine that it does not have permissions to that directory.

**Comment by jni** [comment]
*Why* it would choose that directory, I have no idea. It makes very little sense. =\

**Comment by GenevieveBuckley** [comment]
Yep, this is the cause: https://github.com/chriskiehl/Gooey/issues/301
